server:
  port: 8080

spring:
  jpa:
    dtatabase: h2
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl.auto: update
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driver-class-name: org.h2.Driver

  messages:
    basename: i18n/exception
    encoding: UTF-8
